pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=master
          - status-success=continuous-integration/travis-ci/pr
      actions:
          merge:
              method: merge