pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=master
          - status-success=Travis CI - Pull Request
          - status-success=Travis CI - Branch
      actions:
          merge:
              method: squash
              strict: true