os: linux
dist: bionic
language: csharp
mono: none
dotnet: 3.0
git:
    depth: false

before_install:
    - chmod +x build.sh

script: ./build.sh

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/973db2b10d06f8783310
        on_success: change 
        on_failure: always
        on_start: never