os: linux
dist: bionic
language: csharp
mono: none
dotnet: 3.0
git:
    depth: false

before_install:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - dotnet tool install -g Cake.Tool
    - dotnet tool install -g GitVersion.Tool
    - dotnet tool install -g dotnet-sonarscanner
    - export PATH=$PATH:~/.dotnet/tools
    - chmod +x build.sh
    - dotnet gitversion
    
    
script: ./build.sh
