version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"
steps:
  clone:
    stage: "clone"
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "RoyGI/MLambda"
  build:
    stage: "build"
    type: "build"
    title: "Creating the build images"
    image_name: "build"
    working_directory: "MLambda"
    dockerfile: "build/Dockerfile"
  deploy:
    stage: "deploy"
    type: "freestyle"
    title: "Executing cake"
    image: ${{build}}
    working_directory: MLambda
    environment: 
      - SONARKEY=${{SONARKEY}}
      - APIKEY=${{APIKEY}}
      - BRANCH=${{CF_BRANCH}}
      