apiVersion: skaffold/v1beta16
kind: Config

metadata:
    name: interview

build:
    artifacts:

        - image: roygi-docker-mdocker.bintray.io/actors
          context: docs
          docker:
              dockerfile: deploy/Dockerfile

deploy:
    kubectl:
        manifests:
            - k8s/docs.yml
            - k8s/ingress.yml